import{a as y,S as h,i as c}from"./assets/vendor-Dy2ZTtfi.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const g="https://pixabay.com/api/",L="50890358-614794b793de10968b1ca8154";async function d(t,n=1,s=15){try{return(await y.get(g,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:s}})).data}catch(o){console.log(o)}}const b=new h(".gallery a",{captionsData:"alt",captionDelay:250});function S(){b.refresh()}function u(t){const n=t.map(o=>` <li class="gallery-item">
            <a href="${o.largeImageURL}">
                <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
            </a>
            <div class="info">
            <p><span class="span-info">Views</span> <br> ${o.views}</p>
            <p><span class="span-info">Comments</span> <br> ${o.comments}</p>
            <p><span class="span-info">Downloads </span> <br> ${o.downloads}</p>
            <p> <span class="span-info"> Likes </span> <br> ${o.likes}</p>
            </div>
        </li>`).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",n),S()}function q(){const t=document.querySelector(".gallery");t.innerHTML=""}function w(){document.querySelector(".loader").classList.remove("is-hidden")}function v(){document.querySelector(".loader").classList.add("is-hidden")}function $(){document.querySelector(".load-more").classList.remove("is-hidden")}function p(){document.querySelector(".load-more").classList.add("is-hidden")}document.querySelector(".gallery");const f=document.querySelector(".form");document.querySelector("button");const x=document.querySelector(".load-more");document.querySelector('[name="search-text"]');let m="",a=1,l=15;async function M(t){t.preventDefault();const n=t.currentTarget.elements["search-text"].value;m=n,a=1,q(),w();try{const s=await d(n);if(s.hits.length===0)return c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"});p(),u(s.hits),$(),f.reset()}catch(s){c.error({message:`${s}`,position:"topLeft"})}finally{v()}}async function P(t){t.preventDefault();const n=document.querySelector(".gallery-item");a+=1;const o=n.getBoundingClientRect().height;try{const e=await d(m,a,l),r=Math.ceil(e.totalHits/l);if(a>r)return p(),c.error({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"});u(e.hits),window.scrollBy({top:o*2,behavior:"smooth"})}catch(e){c.error({message:`${e}`,position:"topLeft"})}}f.addEventListener("submit",M);x.addEventListener("click",P);
//# sourceMappingURL=index.js.map
